DEFAULT_CONFIDENCE = 100.0

DEFAULT_PINCODE = "411001"

MAX_BATCH_SIZE = 500

DEFAULT_PRIORITY = "HIGH"

DEFAULT_INCIDENT_STATUS = "DETECTED"

DEFAULT_TICKET_STATUS = "OPEN"

DEFAULT_EVENT = "heartbeat"

CITY_NAME = "Pune"

LATITUDE_OFFSET = 0.02

LONGITUDE_OFFSET = 0.02